### ISSUE TITLE
Load FPGA remote

### ISSUE THREAD

**Issue by qarlosalberto** [PyFPGA/pyfpga#25]
It would be really interesting to be able to load the FPGA remotely.

**Comment by rodrigomelo9** [comment]
Hi @qarlosalberto sorry for the delay (I didn't receive a notification, my fault, now well configured). Could you provide me further information, maybe an example?

**Comment by qarlosalberto** [comment]
Hi :)

With Vivado (I don't know if it's the same with other) is possible to have a HW Server Manager running in a remote machine. So you can load the bitstream remotely. 

Page 25: https://www.xilinx.com/support/documentation/sw_manuals/xilinx2018_3/ug908-vivado-programming-debugging.pdf

**Comment by rodrigomelo9** [comment]
Ok, I know what you are talking about, and as you, not sure about other vendors. Let me see what can I do.

**Comment by rodrigomelo9** [comment]
I will rewrite/simplify PyFPGA. Part of this simplification will include supporting only common scenarios of FPGA programming, not memories, not remote, etc. The aim of PyFPGA is to simplify/abstract bitstream generation, and programming is there only to quickly check the result.
