### ISSUE TITLE
Verify windows support

### ISSUE THREAD

**Issue by rodrigomelo9** [PyFPGA/pyfpga#3]

**Comment by motty-mio2** [comment]
I found a problem on windows.
So I made a pull-request https://github.com/PyFPGA/pyfpga/pull/19#issue-576159749

**Comment by rodrigomelo9** [comment]
Hi @motty-mio2 again thanks (merged, whit a modification to only be applied in Tcl files). It was the only change that you needed? PyFPGA works for you in Windows with Vivado?

Regards,
Rodrigo

**Comment by motty-mio2** [comment]
Thank you for this merge.
With this change, I can generate bitstream file for FPGA in Windows with Vivado. Thanks.

**Comment by rodrigomelo9** [comment]
Great to know :-D

I could probably add a CI action to check the python part on windows, also the [openflow](https://github.com/PyFPGA/openflow) solution (based on FOSS and solved from a bash script), but I can't check the vendor tools there. I need to add some kind of Tcl verification (such as to check the file separators).

Again, thanks to you.

**Comment by gts-bzi** [comment]
Tested PR #43 by Markus on Windows (commit 65b43b8) and it seems to work when pytest is ran in pyfpga/tests.
Running `pytest tests` in project root does not seem to work as pytest ignores the `tests` directory.
Might be helpful to fix in the readme.

**Comment by rodrigomelo9** [comment]
Fixed (you can run pytest also from project root now).

**Comment by rodrigomelo9** [comment]
Fixed on dev
